# Generated by Django 2.0.2 on 2018-03-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursedetail_lecturdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=120)),
                ('section', models.CharField(max_length=120)),
                ('course_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDetail')),
            ],
        ),
    ]
