# Generated by Django 2.0.2 on 2018-03-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180331_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdetail',
            name='total',
        ),
        migrations.AddField(
            model_name='quiz',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
