# Generated by Django 2.0.2 on 2018-03-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180331_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdetail',
            name='questionNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
