# Generated by Django 2.0.2 on 2018-03-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20180331_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='total',
            new_name='totalQuestion',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='questionAnseredCorrectly',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='questionAnswered',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='competionStatus',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
