# Generated by Django 2.0.2 on 2018-04-07 06:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_auto_20180331_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_loop_id', models.IntegerField(blank=True)),
                ('lecture_loop_id', models.IntegerField(blank=True)),
                ('lastAccessed', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.LectureDetail')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
