# Generated by Django 2.0.2 on 2018-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='lecture_loop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='section_loop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
