# Generated by Django 2.0.2 on 2018-04-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180407_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='lecture_loop_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='section_loop_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
