# Generated by Django 2.0.2 on 2018-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20180407_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='lecture_loop_id',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='section_loop_id',
        ),
    ]
